/**
 * Parse 经史百家杂钞.txt into SQL INSERT statements for xz_du_passages.
 *
 * Usage:
 *   npx tsx scripts/parse-jingshi.ts
 */

import { writeFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { fileURLToPath } from 'url'
import { parseJingshiPassages } from './jingshi-parser'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

function generateSQL() {
  const input = resolve(__dirname, '../data/经史百家杂钞.txt')
  const passages = parseJingshiPassages(input)

  const header = `-- Auto-generated by scripts/parse-jingshi.ts
-- Source: data/经史百家杂钞.txt (流芳阁 digitized edition)
-- ${passages.length} passages

INSERT INTO xz_du_passages (source_book, source_origin, title, content, difficulty, theme, volume, enabled)
VALUES`

  const rows = passages.map(
    (p) =>
      `  (${sqlStr(p.source_book)}, ${sqlStr(p.source_origin)}, ${sqlStr(p.title)}, ${sqlStr(p.content)}, ${p.difficulty}, ${sqlStr(p.theme)}, ${p.volume}, true)`
  )

  const byTheme = passages.reduce<Record<string, number>>((acc, p) => {
    acc[p.theme] = (acc[p.theme] ?? 0) + 1
    return acc
  }, {})

  const lengths = passages.map((p) => p.content.length)
  const avg = Math.round(lengths.reduce((a, b) => a + b, 0) / lengths.length)
  const max = Math.max(...lengths)
  const min = Math.min(...lengths)

  process.stderr.write(`Parsed ${passages.length} passages\n`)
  process.stderr.write(`Content length — min: ${min}  avg: ${avg}  max: ${max}\n`)
  process.stderr.write('Theme breakdown:\n')
  for (const [theme, count] of Object.entries(byTheme)) {
    process.stderr.write(`  ${theme}: ${count}\n`)
  }

  return `${header}\n${rows.join(',\n')}\n;\n`
}

const output = resolve(__dirname, '../supabase/seeds/du-passages.sql')
writeFileSync(output, generateSQL(), 'utf-8')
process.stderr.write(`Written to ${output}\n`)
